### PR TITLE
Update Sake implementation to avoid having to call run()

### PR DESCRIPTION
**Pull request by pepibumur**
### Short description 📝
Before this change, developers needed to call `run` in their `Sake` instance to run the tasks. This PR updates the init to implicitly run the tasks so that developers don't have to call run explicitly. Moreover, this solves the issues when you Xcode threw an error saying that the `run()` expression can only be used in a `main.swift` file.

### Implementation 👩‍💻👨‍💻
- [x] Update implementation to avoid having to call run.
- [x] Update tests accordingly.
- [x] Update README.
- [x] Update `GenerateSakefile`.
- [x] Update the project generation to add a dummy `main.swift` file to the target *(otherwise the project doesn't compile)*

### GIF
gif

### CODE REVIEW

**Comment by pepibumur** [comment]
Weird.. when I try to run the project with Xcode now I get this warning in the console:

```
Class _SwiftNull is implemented in both /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib (0x1011d5dd0) and /Users/pepibumur/code/sake/Build/Products/Debug/Sakefile (0x1005b9688). One of the two will be used. Which one is undefined.
objc[95143]: Class _SwiftNativeNSArrayBase is implemented in both /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib (0x1011d5e20) and /Users/pepibumur/code/sake/Build/Products/Debug/Sakefile (0x1005b96d8). One of the two will be used. Which one is undefined.
```

It seems that Swift is being linked from two places but I can't figure which setting is causing it. Any ideas @yonaskolb / @rahul-malik ?

**Comment by pepibumur** [comment]
Solved it with the following build settings:

```swift
"LD_RUNPATH_SEARCH_PATHS": "$(TOOLCHAIN_DIR)/usr/lib/swift/macosx @executable_path",
"SWIFT_FORCE_DYNAMIC_LINK_STDLIB": true,
"SWIFT_FORCE_STATIC_LINK_STDLIB": false,
```

**Comment by polac24** [comment]
Just to let you know: in the meantime I found another solution for this issue by using Custom Build Rule:
* Process with names matching `*Sakefile.swift`
* Using custom script (something like): 
```
mkdir -p generated
cp Sakefile.swift generated/main.swift
chmod 444 generated/main.swift
```
* Output files: `$(SRCROOT)/generated/main.swift`

I planned to add support for Custom Build Rules to `xcproj` and above fix to `sake`, but seems that these have been already addressed.

**Comment by pepibumur** [comment]
Hi @polac24! that's a good idea. I ended up generating a `main.swift` file in a temporary folder in the system. That file gets added together with the `Sakefile.swift` to the project as source files. I'll keep this solution in mind in case the current work doesn't work at all or developers find issues with it.

**Pull request merged**
