### PR TITLE
[WIP] Terminate shell tasks when Sake is interrupted

### PR DESCRIPTION
**Pull request by pepibumur**
Resolves https://github.com/xcodeswift/sake/issues/40

### Short description 📝
When Sake execution is interrupted with CTRL+C, initiated shell processes are not terminated.

### Solution 📦
Listen to system signals and terminate any shell process instantly.

### Implementation 👩‍💻👨‍💻
- [x] Add IBM [BlueSignals](https://github.com/IBM-Swift/BlueSignals)
- [x] Keep a reference to the running processes.
- [ ] Subscribe to signals and terminate the processes when Sake execution is interrupted.

### GIF
gif

### CODE REVIEW

**Comment by pepibumur** [comment]
I'm a bit stack with terminating the processes. I'm trying to do this:

```
init(executor: @escaping Executor = Shell.executor) {
        self.executor = executor
        Signals.trap(signal: .int) { (xx) in
            // Terminate any running process.
        }
  }
```

However, since trap takes a C function and not a closure I can't access the running process to terminate it. I've looked up for a way to solve this but I couldn't find any. Any ideas cc @alexito4

**Comment by dcordero** [comment]
Back to a mac, I was able to take a deeper look into this...

I found the same problem with the closure, it seems to appear only when having a reference to `self`. Looking for it in GitHub I found some guys that workaround it with a static reference to the process so it can be accessed from the closure without referencing to `self`

```
git diff Sources/SakefileUtils/Shell.swift
diff --git a/Sources/SakefileUtils/Shell.swift b/Sources/SakefileUtils/Shell.swift
index 383f266..57aacdd 100644
--- a/Sources/SakefileUtils/Shell.swift
+++ b/Sources/SakefileUtils/Shell.swift
@@ -1,4 +1,5 @@
 import Foundation
+import Signals

 /// Shell error
 public struct ShellError: Error, CustomStringConvertible {
@@ -101,7 +102,13 @@ class ShellCommandExecutor {
     let outputStream: StandardOutOutputStream

     /// Process.
-    let process: Process
+    var process: Process {
+        didSet {
+            ShellCommandExecutor.killMe = process
+        }
+    }
+
+    weak static var killMe: Process?

     /// Launcher
     let launcher: ProcessLauncher
@@ -125,6 +132,11 @@ class ShellCommandExecutor {
         process.standardOutput = pipe
         process.standardError = pipe
         self.launcher = launcher
+
+        Signals.trap(signal: .int) { signal in
+            ShellCommandExecutor.killMe?.terminate()
+            exit(-1)
+        }
     }

     /// Executes the command.
```

With this patch I got it stoping with a SIGINT signal. But only when running the inner command ran by RunSakefile::execture, that mean the following command.

```
/bin/bash -c exec 2>/dev/null; swiftc --driver-mode=swift -L /Users/dcordero/Sources/sake/.build/debug -I /Users/dcordero/Sources/sake/.build/debug -lSakefileUtils /Users/dcordero/Sources/sake/Sakefile.swift task myTask
```

When running sake, I was not able to capture the signals. So I suspect there might be a similar problem when using `runBashCommand` in RunSakefile, not killing the ran bash command when its executor dies. Inception !!! 😄

**Comment by dcordero** [comment]
I made a simple playground project using SwiftShell launching the command "yes". 

As a result of that, I found that the following code (using the same method from ShiftShell than RunSakefile) does not stop with Control+C and it continues printing "yes" on the console until it is manually killed.

```
import SwiftShell

try? main.runAndPrint(bash: "yes")
```

Also tried to replacing bash with the launched command adding exec to the command, but `yes` is not stoping either in this case:
```
import SwiftShell

try? main.runAndPrint(bash: "exec yes")
```

On the other hand, the following code does kill `yes` when pressing Control+C :thinking:

```
let command = main.runAsync("yes")
command.stdout.onOutput { stdout in
    print(stdout)
}

try? command.finish()
```

**Comment by pepibumur** [comment]
Hey @dcordero. Sorry that I couldn't reply earlier. Using the static approach worked and I was able to cancel the running shell task. However, we need to do the same with the bash execution in the `RunSakefile` as you pointed out. Since SwiftShell doesn't work as expected I was thinking about using our `Shell.swift` implementation that supports cancellation. What do you think?

**Comment by dcordero** [comment]
@pepibumur that is a good idea. It would also allow reducing the number of third party dependencies... So, win win

**Comment by pepibumur** [comment]
I've closed this one in favor of https://github.com/xcodeswift/sake/pull/50

**Pull request closed without merging**
