### PR TITLE
Add user input option to Shell

### PR DESCRIPTION
**Pull request by Dschee**
Attempts to resolve https://github.com/xcodeswift/sake/issues/52

### Short description 📝
This adds a `ask(message:)` method to the Shell class to ask for user input.

### Solution 📦
The solution simply uses the `print` and `readLine` commands in Swift.

### Implementation 👩‍💻👨‍💻
- [x] Implement the `ask(message:)` method
- [ ] Test that the ask method works

Please note that in my tests the `readLine()` never stopped from reading, I just doesn't return at all, I don't know why though ... do you have any idea? Does sake somehow block `readLine()` from working?

### CODE REVIEW

**Comment by pepibumur** [comment]
Hi @Dschee! this is a great idea. The reason why it doesn't work is that when Sake runs the Swift file the keyboard input is not properly hooked. There's already [an issue](https://github.com/xcodeswift/sake/issues/52) open to address that. @Juanpe asked on Slack whether there's anyone working on that already. You can maybe coordinate with him to fix it since it's blocking this PR.

**Comment by Juanpe** [comment]
Hi @Dschee, I need this feature to add another one. Could we coordinate to try fix it?

**Comment by Dschee** [comment]
I'll join Slack and contact you there, then.

**Comment by pepibumur** [comment]
@Dschee could you try to rebase from master and see if the input works now?

**Comment by Dschee** [comment]
@pepibumur Thanks for the change. Unfortunately after getting into your slack I saw the link in the #sake channel and found https://github.com/yonaskolb/Beak which I find works perfectly fine for my requirements. I have already finished the initial work I wanted to do with sake, but with beak. So I will probably not have the time to do any more work for sake, sorry for that.

By the way, this is what I ended up with for now using beak:
https://github.com/JamitLabs/NewProjectTemplate-iOS/blob/stable/beak.swift

**Comment by pepibumur** [comment]
No problem @Dschee I'll take it over!

**Pull request closed without merging**
